# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70d7511cd0375f875fdb94819706b1bec8ca7f951074be9863e3a1a90969a66cd965199a1d978cf66e1c9aa04d54966d24921d512808ea5061f36a6519bd59d1

test:
  secret_key_base: 40b3e25eed28dfa62085acdd3b3274c3775e0d3db5f578c4d5b3d7d3e735a53fafe519f7c6aea1cbec97fa593998133f0ccbe9fcd2c567cd6b39d068b854f12e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
